var translation = {
    'unauthorized': "Wrong username or password",
    'error': 'Error name not resolved: {0}',
    'passwordNotTheSame': 'Passwords are not the same',
    'passwordChanged': 'Password has been changed',
    'avatar_uploaded': 'Avatar has been updated',
    'profileUpdated': 'Profile details has been updated',
    'avatar_required_ext': 'Please upload only JPG and PNG',
    'avatar_maximum_size': 'Maximum file size is 1Mb',
    'something_gone_wrong': 'Ups, something gone wrong',
    'are_you_sure': 'Are you sure?',
    'delete_account': 'Delete account',
    'yes': 'Yes',
    'forgot_password': 'Check your email to set new password',
    'applicationCreated': 'Application has been created',
    'apiKeyCopiedToClipboard': 'Api key copied to clipboard',
    'deleteApplication': 'Delete application',
    'applicationDeleted': 'The application has been removed',
    'optionsUpdated': 'Security options has been updated',
    'hash_length_min_value': 'Minimum hash length should be 10',
    'hash_length_max_value': 'Maximum hash length should be 500',
    'hash_length_min_higher': 'Maximum hash length should be higher than minimum',
    'salt_required': 'Salt hash is required when not random',
    'productionMode': 'Production mode',
    'confirmEnableProductionMode': 'Are you sure to switch to production mode? You will not be able to modify settings and queries during this mode',
    'confirmDisableProductionMode': 'Are you sure to disable production mode? This can switch off your applications using JSQL',
    'productionEnabled': 'Production mode has been enabled',
    'productionDisabled': 'Production mode has been disabled',
    'delete_developer' : 'Remove developer',
    'developer_deleted' : 'Developer has been removed',
    'developer_created' : 'Developer has been created'
};