'use strict';

var translation = {
    'unauthorized': "Wrong username or password",
    'error': 'Error name not resolved: {0}',
    'passwordNotTheSame': 'Passwords are not the same',
    'passwordChanged': 'Password has been changed',
    'avatar_uploaded': 'Avatar has been updated',
    'profileUpdated': 'Profile details has been updated',
    'avatar_required_ext': 'Please upload only JPG and PNG',
    'avatar_maximum_size': 'Maximum file size is 1Mb',
    'something_gone_wrong': 'Ups, something gone wrong',
    'are_you_sure': 'Are you sure?',
    'are_you_sure_demote_admin' : 'Are you sure? Admin will become developer with privileges to all applications',
    'demote_admin' : 'Demote admin',
    'are_you_sure_advance_developer' : 'Are you sure? Developer will become administrator with privileges to all applications',
    'advance_developer' : 'Advance developer',
    'delete_account': 'Delete account',
    'yes': 'Yes',
    'forgot_password': 'Check your email to set new password',
    'applicationCreated': 'Application has been created',
    'apiKeyCopiedToClipboard': 'Api key copied to clipboard',
    'deleteApplication': 'Delete application',
    'applicationDeleted': 'The application has been removed',
    'optionsUpdated': 'Security options has been updated',
    'hash_length_min_value': 'Minimum hash length should be 10',
    'hash_length_max_value': 'Maximum hash length should be 500',
    'hash_length_min_higher': 'Maximum hash length should be higher than minimum',
    'salt_required': 'Salt hash is required when not random',
    'productionMode': 'Production mode',
    'confirmEnableProductionMode': 'Are you sure to switch to production mode? You will not be able to modify settings and queries during this mode',
    'confirmDisableProductionMode': 'Are you sure to disable production mode? This can switch off your applications using JSQL',
    'productionEnabled': 'Production mode has been enabled',
    'productionDisabled': 'Production mode has been disabled',
    'delete_developer' : 'Remove developer',
    'developer_deleted' : 'Developer has been removed',
    'developer_created' : 'Developer has been created',
    'account_activated' : 'Your account has been activated',
    'activation_failed' : 'Activation failed. Please contact support',
    'delete_admin' : 'Remove administrator',
    'admin_deleted' : 'Administrator has been removed',
    'admin_created' : 'Administrator has been created',
    'queryUpdated' : 'Query has been updated',
    'developerKeyCopiedToClipboard': 'Developer key copied to clipboard',
    'yourDeveloperKeyForDevelopment' : 'This is your developer key for development purposes',
    'onlyDevelopmentKeyProductionKeyForApp': 'This is your developer key for development purposes. For production purposes, use production key from application details',
    'applicationInProduction' : 'Application is in production, cannot delete and use for development purposes',
    'productionKeyCopiedToClipboard' : 'Production key copied to clipboard',
    'productionKeyInfo' : 'This is production key for production purposes. For development purposes, use your development key',
    'securityInfo' : 'By default, security settings are balanced between performance and data security',
    'username_unavailable' : 'Provided first name and last name is already in use in this company',
    'thank_you_feedback' : 'Thank you for feedback',
    'invalid_dates' : 'Invalid dates provided',
    'copied_title' : 'Copied',
    'copied_message' : 'Copied to clipboard'
};